import type { Client } from "./types"

export const mockClients: Client[] = [
  {
    id: "c1",
    companyName: "TechVault Co.",
    contactName: "Jason Merritt",
    email: "jason@techvault.co",
    phone: "(310) 555-0182",
    status: "Active",
    loginStatus: "Active",
    lastActivity: "May 27, 2026",
    notes: "Priority client. Rush requests approved.",
    invitedAt: "Jan 12, 2026",
  },
  {
    id: "c2",
    companyName: "NovaTrade Ltd.",
    contactName: "Sandra Voss",
    email: "ap@novatrade.com",
    phone: "(626) 555-0347",
    status: "Active",
    loginStatus: "Active",
    lastActivity: "May 26, 2026",
    notes: "",
    invitedAt: "Feb 3, 2026",
  },
  {
    id: "c3",
    companyName: "BrightBox LLC",
    contactName: "Marcus Liu",
    email: "finance@brightbox.io",
    phone: "(213) 555-0094",
    status: "Active",
    loginStatus: "Invited",
    lastActivity: "May 20, 2026",
    notes: "Pending portal onboarding. Follow up needed.",
    invitedAt: "May 15, 2026",
  },
  {
    id: "c4",
    companyName: "Stellar Goods",
    contactName: "Priya Nair",
    email: "accounts@stellargoods.com",
    phone: "(909) 555-0561",
    status: "Active",
    loginStatus: "No Login",
    lastActivity: "Apr 28, 2026",
    notes: "Prefers email communication. Not yet onboarded to portal.",
  },
  {
    id: "c5",
    companyName: "PrimePack Inc.",
    contactName: "Derek Walsh",
    email: "derek@primepack.io",
    phone: "(714) 555-0239",
    status: "Pending",
    loginStatus: "No Login",
    lastActivity: null,
    notes: "Signed agreement Apr 2026. Awaiting first shipment.",
  },
  {
    id: "c6",
    companyName: "OrbitSell Ltd.",
    contactName: "Camille Bernard",
    email: "cbernard@orbitsell.com",
    phone: "(424) 555-0873",
    status: "Inactive",
    loginStatus: "Active",
    lastActivity: "Jan 14, 2026",
    notes: "Account on hold — payment dispute resolved. Reactivate when ready.",
    invitedAt: "Sep 8, 2025",
  },
]
