import type { Invoice } from "./types"

export const mockInvoices: Invoice[] = [
  {
    id: "inv-41",
    invoiceNumber: "INV-0041",
    clientId: "c1",
    clientName: "TechVault Co.",
    clientEmail: "billing@techvault.co",
    clientAddress: "4200 Commerce Blvd, Suite 110\nLos Angeles, CA 90021",
    date: "May 22, 2026",
    dueDate: "Jun 5, 2026",
    status: "Unpaid",
    lineItems: [
      { id: "li1", description: "FBA Prep – Wireless Earbuds (500 units)", quantity: 500, unitPrice: 0.85 },
      { id: "li2", description: "Poly Bag + Bubble Wrap Materials", quantity: 1, unitPrice: 45.00 },
      { id: "li3", description: "Rush Processing Fee", quantity: 1, unitPrice: 75.00 },
    ],
    notes: "Payment due within 14 days. ACH or wire transfer preferred.",
    relatedRequestNumber: "REQ-2005",
  },
  {
    id: "inv-40",
    invoiceNumber: "INV-0040",
    clientId: "c2",
    clientName: "NovaTrade Ltd.",
    clientEmail: "ap@novatrade.com",
    clientAddress: "888 Industrial Pkwy\nCity of Industry, CA 91748",
    date: "May 17, 2026",
    dueDate: "May 31, 2026",
    status: "Overdue",
    lineItems: [
      { id: "li4", description: "Labeling Service – Stainless Steel Tumbler (300 units)", quantity: 300, unitPrice: 0.45 },
      { id: "li5", description: "Label Materials – Custom Die-Cut", quantity: 300, unitPrice: 0.12 },
      { id: "li6", description: "Storage Fee – May 1–17 (15 pallets)", quantity: 15, unitPrice: 22.00 },
    ],
    notes: "Payment is now overdue. Please remit immediately to avoid service hold.",
    relatedRequestNumber: "REQ-2004",
  },
  {
    id: "inv-39",
    invoiceNumber: "INV-0039",
    clientId: "c3",
    clientName: "BrightBox LLC",
    clientEmail: "finance@brightbox.io",
    clientAddress: "12 Warehouse Row\nCompton, CA 90220",
    date: "May 10, 2026",
    dueDate: "May 24, 2026",
    status: "Paid",
    lineItems: [
      { id: "li7", description: "FBA Prep – Yoga Mat (200 units)", quantity: 200, unitPrice: 1.20 },
      { id: "li8", description: "Poly Bag Materials", quantity: 200, unitPrice: 0.18 },
      { id: "li9", description: "Inbound Receiving Fee", quantity: 1, unitPrice: 35.00 },
    ],
    notes: "Payment received via ACH on May 23, 2026. Thank you!",
    relatedRequestNumber: "REQ-2002",
  },
  {
    id: "inv-38",
    invoiceNumber: "INV-0038",
    clientId: "c2",
    clientName: "NovaTrade Ltd.",
    clientEmail: "ap@novatrade.com",
    clientAddress: "888 Industrial Pkwy\nCity of Industry, CA 91748",
    date: "May 5, 2026",
    dueDate: "May 19, 2026",
    status: "Paid",
    lineItems: [
      { id: "li10", description: "FBA Prep – Resistance Band Set (250 units)", quantity: 250, unitPrice: 0.80 },
      { id: "li11", description: "FNSKU Label Application", quantity: 250, unitPrice: 0.10 },
    ],
    notes: "Wire transfer received May 18, 2026.",
    relatedRequestNumber: "REQ-2001",
  },
  {
    id: "inv-37",
    invoiceNumber: "INV-0037",
    clientId: "c4",
    clientName: "Stellar Goods",
    clientEmail: "accounts@stellargoods.com",
    clientAddress: "300 Fulton St, Unit 5\nOntario, CA 91762",
    date: "Apr 28, 2026",
    dueDate: "May 12, 2026",
    status: "Paid",
    lineItems: [
      { id: "li12", description: "Inspection Service – Wireless Earbuds (100 units)", quantity: 100, unitPrice: 1.50 },
      { id: "li13", description: "Detailed Inspection Report", quantity: 1, unitPrice: 55.00 },
    ],
    notes: "",
    relatedRequestNumber: "REQ-2000",
  },
  {
    id: "inv-36",
    invoiceNumber: "INV-0036",
    clientId: "c2",
    clientName: "NovaTrade Ltd.",
    clientEmail: "ap@novatrade.com",
    clientAddress: "888 Industrial Pkwy\nCity of Industry, CA 91748",
    date: "Apr 20, 2026",
    dueDate: "May 4, 2026",
    status: "Paid",
    lineItems: [
      { id: "li14", description: "Labeling Service – Stainless Steel Tumbler Batch 2 (150 units)", quantity: 150, unitPrice: 0.45 },
      { id: "li15", description: "Storage Fee – Apr 1–20 (10 pallets)", quantity: 10, unitPrice: 22.00 },
    ],
    notes: "Paid via check #4492.",
    relatedRequestNumber: "REQ-1999",
  },
  {
    id: "inv-35",
    invoiceNumber: "INV-0035",
    clientId: "c1",
    clientName: "TechVault Co.",
    clientEmail: "billing@techvault.co",
    clientAddress: "4200 Commerce Blvd, Suite 110\nLos Angeles, CA 90021",
    date: "Apr 10, 2026",
    dueDate: "Apr 24, 2026",
    status: "Void",
    lineItems: [
      { id: "li16", description: "FBA Prep – LED Desk Lamp (100 units)", quantity: 100, unitPrice: 0.90 },
      { id: "li17", description: "Bundling – Lamp + Cable Combo", quantity: 50, unitPrice: 1.25 },
    ],
    notes: "Voided — duplicate of INV-0034. Please disregard.",
  },
  {
    id: "inv-34",
    invoiceNumber: "INV-0034",
    clientId: "c3",
    clientName: "BrightBox LLC",
    clientEmail: "finance@brightbox.io",
    clientAddress: "12 Warehouse Row\nCompton, CA 90220",
    date: "Apr 5, 2026",
    dueDate: "May 26, 2026",
    status: "Unpaid",
    lineItems: [
      { id: "li18", description: "Storage Fee – Q1 2026 (20 pallets × 3 months)", quantity: 60, unitPrice: 22.00 },
      { id: "li19", description: "Pallet Wrap Materials", quantity: 20, unitPrice: 4.50 },
    ],
    notes: "Extended terms approved for Q1 storage. Due May 26.",
  },
]
