import type { ServiceRequest } from "./types"

export const mockRequests: ServiceRequest[] = [
  {
    id: "r1",
    requestNumber: "REQ-2005",
    clientId: "c1",
    clientName: "TechVault Co.",
    productId: "p1",
    productName: "Wireless Earbuds",
    productSku: "WE-1000",
    service: "FBA Prep",
    services: [],
    quantity: 500,
    status: "In Progress",
    files: [
      { id: "f1", name: "FNSKU_Labels_Earbuds.pdf", type: "pdf", size: "245 KB" },
      { id: "f2", name: "Box_Labels_WE1000.pdf", type: "pdf", size: "180 KB" },
    ],
    notes: "Priority rush — needed by Jun 3.",
    serviceDetails: { prepNotes: "Poly bag + bubble wrap each unit." },
    createdAt: "May 27, 2026",
    inventoryDeducted: true,
  },
  {
    id: "r2",
    requestNumber: "REQ-2004",
    clientId: "c2",
    clientName: "NovaTrade Ltd.",
    productId: "p2",
    productName: "Stainless Steel Tumbler",
    productSku: "TMB-500",
    service: "Labeling",
    services: [],
    quantity: 300,
    status: "New",
    files: [
      { id: "f3", name: "Label_Sheet_Tumbler.pdf", type: "pdf", size: "130 KB" },
    ],
    notes: "",
    serviceDetails: { placementNotes: "Apply label on bottom of product." },
    createdAt: "May 26, 2026",
    inventoryDeducted: true,
  },
  {
    id: "r3",
    requestNumber: "REQ-2003",
    clientId: "c1",
    clientName: "TechVault Co.",
    productId: "p3",
    productName: "Phone Case iPhone 14",
    productSku: "PC-14-BLK",
    service: "Bundling",
    services: [],
    quantity: 200,
    status: "New",
    files: [],
    notes: "",
    serviceDetails: {
      bundleInstructions: "Bundle 2 units per pack with branded insert.",
      unitsPerBundle: 2,
    },
    createdAt: "May 25, 2026",
    inventoryDeducted: true,
  },
  {
    id: "r4",
    requestNumber: "REQ-2002",
    clientId: "c3",
    clientName: "BrightBox LLC",
    productId: "p4",
    productName: "Yoga Mat",
    productSku: "YM-200",
    service: "FBA Prep",
    services: [],
    quantity: 200,
    status: "Completed",
    files: [
      { id: "f4", name: "FNSKU_Labels_YogaMat.pdf", type: "pdf", size: "210 KB" },
      { id: "f5", name: "Prep_Instructions_YM200.pdf", type: "pdf", size: "95 KB" },
      { id: "f6", name: "Box_Labels_YM200.pdf", type: "pdf", size: "165 KB" },
    ],
    notes: "",
    serviceDetails: { prepNotes: "Poly bag required." },
    createdAt: "May 24, 2026",
    inventoryDeducted: true,
  },
  {
    id: "r5",
    requestNumber: "REQ-2001",
    clientId: "c2",
    clientName: "NovaTrade Ltd.",
    productId: "p5",
    productName: "Resistance Band Set",
    productSku: "RB-SET",
    service: "FBA Prep",
    services: [],
    quantity: 250,
    status: "Completed",
    files: [
      { id: "f7", name: "FNSKU_Labels_RBSet.pdf", type: "pdf", size: "198 KB" },
    ],
    notes: "",
    serviceDetails: {},
    createdAt: "May 22, 2026",
    inventoryDeducted: true,
  },
  {
    id: "r6",
    requestNumber: "REQ-2000",
    clientId: "c4",
    clientName: "Stellar Goods",
    productId: "p1",
    productName: "Wireless Earbuds",
    productSku: "WE-1000",
    service: "Inspection",
    services: [],
    quantity: 100,
    status: "Need Attention",
    files: [],
    notes: "Waiting on updated inspection criteria from client.",
    serviceDetails: {},
    createdAt: "May 20, 2026",
    inventoryDeducted: true,
  },
  {
    id: "r7",
    requestNumber: "REQ-1999",
    clientId: "c2",
    clientName: "NovaTrade Ltd.",
    productId: "p2",
    productName: "Stainless Steel Tumbler",
    productSku: "TMB-500",
    service: "Labeling",
    services: [],
    quantity: 150,
    status: "Invoiced",
    files: [
      { id: "f8", name: "Label_Tumbler_Batch2.pdf", type: "pdf", size: "120 KB" },
    ],
    notes: "",
    serviceDetails: { placementNotes: "Side label placement." },
    createdAt: "May 17, 2026",
    inventoryDeducted: true,
  },
]
