import type { FileDoc } from "./types"

// Derived from service requests (r1, r2, r4, r5, r7) + shipments + extras
export const mockFiles: FileDoc[] = [
  // ── From REQ-2005 (TechVault Co., FBA Prep – Wireless Earbuds)
  {
    id: "fd1",
    name: "FNSKU_Labels_Earbuds.pdf",
    ext: "pdf",
    size: "245 KB",
    category: "Labels",
    relatedTo: "REQ-2005",
    relatedType: "service-request",
    relatedId: "r1",
    clientId: "c1",
    clientName: "TechVault Co.",
    uploadedBy: "TechVault Co.",
    uploadedAt: "May 27, 2026",
  },
  {
    id: "fd2",
    name: "Box_Labels_WE1000.pdf",
    ext: "pdf",
    size: "180 KB",
    category: "Labels",
    relatedTo: "REQ-2005",
    relatedType: "service-request",
    relatedId: "r1",
    clientId: "c1",
    clientName: "TechVault Co.",
    uploadedBy: "TechVault Co.",
    uploadedAt: "May 27, 2026",
  },

  // ── From REQ-2004 (NovaTrade Ltd., Labeling – Stainless Steel Tumbler)
  {
    id: "fd3",
    name: "Label_Sheet_Tumbler.pdf",
    ext: "pdf",
    size: "130 KB",
    category: "Labels",
    relatedTo: "REQ-2004",
    relatedType: "service-request",
    relatedId: "r2",
    clientId: "c2",
    clientName: "NovaTrade Ltd.",
    uploadedBy: "NovaTrade Ltd.",
    uploadedAt: "May 26, 2026",
  },

  // ── From REQ-2002 (BrightBox LLC, FBA Prep – Yoga Mat)
  {
    id: "fd4",
    name: "FNSKU_Labels_YogaMat.pdf",
    ext: "pdf",
    size: "210 KB",
    category: "Labels",
    relatedTo: "REQ-2002",
    relatedType: "service-request",
    relatedId: "r4",
    clientId: "c3",
    clientName: "BrightBox LLC",
    uploadedBy: "BrightBox LLC",
    uploadedAt: "May 24, 2026",
  },
  {
    id: "fd5",
    name: "Prep_Instructions_YM200.pdf",
    ext: "pdf",
    size: "95 KB",
    category: "Product Docs",
    relatedTo: "REQ-2002",
    relatedType: "service-request",
    relatedId: "r4",
    clientId: "c3",
    clientName: "BrightBox LLC",
    uploadedBy: "Safir WMS",
    uploadedAt: "May 24, 2026",
  },
  {
    id: "fd6",
    name: "Box_Labels_YM200.pdf",
    ext: "pdf",
    size: "165 KB",
    category: "Labels",
    relatedTo: "REQ-2002",
    relatedType: "service-request",
    relatedId: "r4",
    clientId: "c3",
    clientName: "BrightBox LLC",
    uploadedBy: "BrightBox LLC",
    uploadedAt: "May 24, 2026",
  },

  // ── From REQ-2001 (NovaTrade Ltd., FBA Prep – Resistance Band Set)
  {
    id: "fd7",
    name: "FNSKU_Labels_RBSet.pdf",
    ext: "pdf",
    size: "198 KB",
    category: "Labels",
    relatedTo: "REQ-2001",
    relatedType: "service-request",
    relatedId: "r5",
    clientId: "c2",
    clientName: "NovaTrade Ltd.",
    uploadedBy: "NovaTrade Ltd.",
    uploadedAt: "May 22, 2026",
  },

  // ── From REQ-1999 (NovaTrade Ltd., Labeling – Tumbler Batch 2)
  {
    id: "fd8",
    name: "Label_Tumbler_Batch2.pdf",
    ext: "pdf",
    size: "120 KB",
    category: "Labels",
    relatedTo: "REQ-1999",
    relatedType: "service-request",
    relatedId: "r7",
    clientId: "c2",
    clientName: "NovaTrade Ltd.",
    uploadedBy: "NovaTrade Ltd.",
    uploadedAt: "May 17, 2026",
  },

  // ── Shipment Docs
  {
    id: "fd9",
    name: "Packing_List_IN1008.pdf",
    ext: "pdf",
    size: "88 KB",
    category: "Shipment Docs",
    relatedTo: "IN-1008",
    relatedType: "shipment",
    relatedId: "s1",
    clientId: "c1",
    clientName: "TechVault Co.",
    uploadedBy: "TechVault Co.",
    uploadedAt: "May 26, 2026",
  },
  {
    id: "fd10",
    name: "Packing_List_IN1007.pdf",
    ext: "pdf",
    size: "72 KB",
    category: "Shipment Docs",
    relatedTo: "IN-1007",
    relatedType: "shipment",
    relatedId: "s2",
    clientId: "c2",
    clientName: "NovaTrade Ltd.",
    uploadedBy: "NovaTrade Ltd.",
    uploadedAt: "May 23, 2026",
  },
  {
    id: "fd11",
    name: "Receiving_Report_IN1005.xlsx",
    ext: "xlsx",
    size: "54 KB",
    category: "Shipment Docs",
    relatedTo: "IN-1005",
    relatedType: "shipment",
    relatedId: "s4",
    clientId: "c3",
    clientName: "BrightBox LLC",
    uploadedBy: "Safir WMS",
    uploadedAt: "May 18, 2026",
  },
  {
    id: "fd12",
    name: "BOL_IN1004.pdf",
    ext: "pdf",
    size: "112 KB",
    category: "Shipment Docs",
    relatedTo: "IN-1004",
    relatedType: "shipment",
    relatedId: "s5",
    clientId: "c4",
    clientName: "Stellar Goods",
    uploadedBy: "Stellar Goods",
    uploadedAt: "May 15, 2026",
  },

  // ── Agreements
  {
    id: "fd13",
    name: "Service_Agreement_TechVault.pdf",
    ext: "pdf",
    size: "320 KB",
    category: "Agreements",
    relatedTo: "TechVault Co.",
    relatedType: "agreement",
    relatedId: "c1",
    clientId: "c1",
    clientName: "TechVault Co.",
    uploadedBy: "Safir WMS",
    uploadedAt: "Apr 10, 2026",
  },
  {
    id: "fd14",
    name: "Terms_NovaTrade.docx",
    ext: "docx",
    size: "85 KB",
    category: "Agreements",
    relatedTo: "NovaTrade Ltd.",
    relatedType: "agreement",
    relatedId: "c2",
    clientId: "c2",
    clientName: "NovaTrade Ltd.",
    uploadedBy: "Safir WMS",
    uploadedAt: "Mar 22, 2026",
  },
  {
    id: "fd15",
    name: "Warehouse_Agreement_BrightBox.pdf",
    ext: "pdf",
    size: "298 KB",
    category: "Agreements",
    relatedTo: "BrightBox LLC",
    relatedType: "agreement",
    relatedId: "c3",
    clientId: "c3",
    clientName: "BrightBox LLC",
    uploadedBy: "Safir WMS",
    uploadedAt: "Mar 5, 2026",
  },

  // ── Invoices
  {
    id: "fd16",
    name: "Invoice_INV-0041.pdf",
    ext: "pdf",
    size: "145 KB",
    category: "Invoices",
    relatedTo: "INV-0041",
    relatedType: "invoice",
    relatedId: "inv-41",
    clientId: "c1",
    clientName: "TechVault Co.",
    uploadedBy: "Safir WMS",
    uploadedAt: "May 22, 2026",
  },
  {
    id: "fd17",
    name: "Invoice_INV-0040.pdf",
    ext: "pdf",
    size: "138 KB",
    category: "Invoices",
    relatedTo: "INV-0040",
    relatedType: "invoice",
    relatedId: "inv-40",
    clientId: "c2",
    clientName: "NovaTrade Ltd.",
    uploadedBy: "Safir WMS",
    uploadedAt: "May 17, 2026",
  },
  {
    id: "fd18",
    name: "Invoice_INV-0039.pdf",
    ext: "pdf",
    size: "121 KB",
    category: "Invoices",
    relatedTo: "INV-0039",
    relatedType: "invoice",
    relatedId: "inv-39",
    clientId: "c3",
    clientName: "BrightBox LLC",
    uploadedBy: "Safir WMS",
    uploadedAt: "May 10, 2026",
  },

  // ── Product Docs / Other
  {
    id: "fd19",
    name: "Product_Spec_WirelessEarbuds.pdf",
    ext: "pdf",
    size: "402 KB",
    category: "Product Docs",
    relatedTo: "Wireless Earbuds",
    relatedType: "product",
    relatedId: "p1",
    clientId: "c1",
    clientName: "TechVault Co.",
    uploadedBy: "TechVault Co.",
    uploadedAt: "Apr 15, 2026",
  },
  {
    id: "fd20",
    name: "Inventory_Checklist_Q2.xlsx",
    ext: "xlsx",
    size: "67 KB",
    category: "Other",
    relatedTo: "General",
    relatedType: "general",
    relatedId: "",
    clientId: "c4",
    clientName: "Stellar Goods",
    uploadedBy: "Stellar Goods",
    uploadedAt: "Apr 2, 2026",
  },
]
